/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountCheckResponseAllOfResultItem
 */
public class AccountCheckResponseAllOfResultItemTest {
    private final AccountCheckResponseAllOfResultItem model = new AccountCheckResponseAllOfResultItem();

    /**
     * Model tests for AccountCheckResponseAllOfResultItem
     */
    @Test
    public void testAccountCheckResponseAllOfResultItem() {
        // TODO: test AccountCheckResponseAllOfResultItem
    }

    /**
     * Test the property 'resultCode'
     */
    @Test
    public void resultCodeTest() {
        // TODO: test resultCode
    }

    /**
     * Test the property 'resultInfo'
     */
    @Test
    public void resultInfoTest() {
        // TODO: test resultInfo
    }

    /**
     * Test the property 'userID'
     */
    @Test
    public void userIDTest() {
        // TODO: test userID
    }

    /**
     * Test the property 'accountStatus'
     */
    @Test
    public void accountStatusTest() {
        // TODO: test accountStatus
    }

}
