/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.BatchSendSingleChatMsgResponseAllOf;
import com.tencentcloudapi.im.model.BatchSendSingleChatMsgResponseAllOfErrorList;
import com.tencentcloudapi.im.model.CommonResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BatchSendSingleChatMsgResponse
 */
public class BatchSendSingleChatMsgResponseTest {
    private final BatchSendSingleChatMsgResponse model = new BatchSendSingleChatMsgResponse();

    /**
     * Model tests for BatchSendSingleChatMsgResponse
     */
    @Test
    public void testBatchSendSingleChatMsgResponse() {
        // TODO: test BatchSendSingleChatMsgResponse
    }

    /**
     * Test the property 'actionStatus'
     */
    @Test
    public void actionStatusTest() {
        // TODO: test actionStatus
    }

    /**
     * Test the property 'errorInfo'
     */
    @Test
    public void errorInfoTest() {
        // TODO: test errorInfo
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'msgTime'
     */
    @Test
    public void msgTimeTest() {
        // TODO: test msgTime
    }

    /**
     * Test the property 'msgKey'
     */
    @Test
    public void msgKeyTest() {
        // TODO: test msgKey
    }

    /**
     * Test the property 'errorList'
     */
    @Test
    public void errorListTest() {
        // TODO: test errorList
    }

}
