/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.BatchSendSingleChatMsgResponseAllOfErrorList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BatchSendSingleChatMsgResponseAllOf
 */
public class BatchSendSingleChatMsgResponseAllOfTest {
    private final BatchSendSingleChatMsgResponseAllOf model = new BatchSendSingleChatMsgResponseAllOf();

    /**
     * Model tests for BatchSendSingleChatMsgResponseAllOf
     */
    @Test
    public void testBatchSendSingleChatMsgResponseAllOf() {
        // TODO: test BatchSendSingleChatMsgResponseAllOf
    }

    /**
     * Test the property 'msgTime'
     */
    @Test
    public void msgTimeTest() {
        // TODO: test msgTime
    }

    /**
     * Test the property 'msgKey'
     */
    @Test
    public void msgKeyTest() {
        // TODO: test msgKey
    }

    /**
     * Test the property 'errorList'
     */
    @Test
    public void errorListTest() {
        // TODO: test errorList
    }

}
