/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.OfflinePushInfo;
import com.tencentcloudapi.im.model.TIMMsgElement;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BatchSendSingleChatMsgRequest
 */
public class BatchSendSingleChatMsgRequestTest {
    private final BatchSendSingleChatMsgRequest model = new BatchSendSingleChatMsgRequest();

    /**
     * Model tests for BatchSendSingleChatMsgRequest
     */
    @Test
    public void testBatchSendSingleChatMsgRequest() {
        // TODO: test BatchSendSingleChatMsgRequest
    }

    /**
     * Test the property 'syncOtherMachine'
     */
    @Test
    public void syncOtherMachineTest() {
        // TODO: test syncOtherMachine
    }

    /**
     * Test the property 'fromAccount'
     */
    @Test
    public void fromAccountTest() {
        // TODO: test fromAccount
    }

    /**
     * Test the property 'toAccount'
     */
    @Test
    public void toAccountTest() {
        // TODO: test toAccount
    }

    /**
     * Test the property 'msgLifeTime'
     */
    @Test
    public void msgLifeTimeTest() {
        // TODO: test msgLifeTime
    }

    /**
     * Test the property 'msgSeq'
     */
    @Test
    public void msgSeqTest() {
        // TODO: test msgSeq
    }

    /**
     * Test the property 'msgRandom'
     */
    @Test
    public void msgRandomTest() {
        // TODO: test msgRandom
    }

    /**
     * Test the property 'sendMsgControl'
     */
    @Test
    public void sendMsgControlTest() {
        // TODO: test sendMsgControl
    }

    /**
     * Test the property 'msgBody'
     */
    @Test
    public void msgBodyTest() {
        // TODO: test msgBody
    }

    /**
     * Test the property 'cloudCustomData'
     */
    @Test
    public void cloudCustomDataTest() {
        // TODO: test cloudCustomData
    }

    /**
     * Test the property 'offlinePushInfo'
     */
    @Test
    public void offlinePushInfoTest() {
        // TODO: test offlinePushInfo
    }

}
