/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tencentcloudapi.im.model.DefinedData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateGroupRequestMemberList
 */
public class CreateGroupRequestMemberListTest {
    private final CreateGroupRequestMemberList model = new CreateGroupRequestMemberList();

    /**
     * Model tests for CreateGroupRequestMemberList
     */
    @Test
    public void testCreateGroupRequestMemberList() {
        // TODO: test CreateGroupRequestMemberList
    }

    /**
     * Test the property 'memberAccount'
     */
    @Test
    public void memberAccountTest() {
        // TODO: test memberAccount
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'joinTime'
     */
    @Test
    public void joinTimeTest() {
        // TODO: test joinTime
    }

    /**
     * Test the property 'msgSeq'
     */
    @Test
    public void msgSeqTest() {
        // TODO: test msgSeq
    }

    /**
     * Test the property 'msgFlag'
     */
    @Test
    public void msgFlagTest() {
        // TODO: test msgFlag
    }

    /**
     * Test the property 'nameCard'
     */
    @Test
    public void nameCardTest() {
        // TODO: test nameCard
    }

    /**
     * Test the property 'lastSendMsgTime'
     */
    @Test
    public void lastSendMsgTimeTest() {
        // TODO: test lastSendMsgTime
    }

    /**
     * Test the property 'appMemberDefinedData'
     */
    @Test
    public void appMemberDefinedDataTest() {
        // TODO: test appMemberDefinedData
    }

}
