/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ForbidCallbackControl
 */
public class ForbidCallbackControlTest {
    /**
     * Model tests for ForbidCallbackControl
     */
    @Test
    public void testForbidCallbackControl() {
        // TODO: test ForbidCallbackControl
    }

}
