/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FriendAddRequestAddFriendItem
 */
public class FriendAddRequestAddFriendItemTest {
    private final FriendAddRequestAddFriendItem model = new FriendAddRequestAddFriendItem();

    /**
     * Model tests for FriendAddRequestAddFriendItem
     */
    @Test
    public void testFriendAddRequestAddFriendItem() {
        // TODO: test FriendAddRequestAddFriendItem
    }

    /**
     * Test the property 'toAccount'
     */
    @Test
    public void toAccountTest() {
        // TODO: test toAccount
    }

    /**
     * Test the property 'remark'
     */
    @Test
    public void remarkTest() {
        // TODO: test remark
    }

    /**
     * Test the property 'groupName'
     */
    @Test
    public void groupNameTest() {
        // TODO: test groupName
    }

    /**
     * Test the property 'addSource'
     */
    @Test
    public void addSourceTest() {
        // TODO: test addSource
    }

    /**
     * Test the property 'addWording'
     */
    @Test
    public void addWordingTest() {
        // TODO: test addWording
    }

}
