/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FriendAddRequestAddFriendItemInner
 */
public class FriendAddRequestAddFriendItemInnerTest {
    private final FriendAddRequestAddFriendItemInner model = new FriendAddRequestAddFriendItemInner();

    /**
     * Model tests for FriendAddRequestAddFriendItemInner
     */
    @Test
    public void testFriendAddRequestAddFriendItemInner() {
        // TODO: test FriendAddRequestAddFriendItemInner
    }

    /**
     * Test the property 'toAccount'
     */
    @Test
    public void toAccountTest() {
        // TODO: test toAccount
    }

    /**
     * Test the property 'remark'
     */
    @Test
    public void remarkTest() {
        // TODO: test remark
    }

    /**
     * Test the property 'groupName'
     */
    @Test
    public void groupNameTest() {
        // TODO: test groupName
    }

    /**
     * Test the property 'addSource'
     */
    @Test
    public void addSourceTest() {
        // TODO: test addSource
    }

    /**
     * Test the property 'addWording'
     */
    @Test
    public void addWordingTest() {
        // TODO: test addWording
    }

}
