/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tencentcloudapi.im.model.FriendUpdateRequestSnsItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FriendUpdateRequestUpdateItem
 */
public class FriendUpdateRequestUpdateItemTest {
    private final FriendUpdateRequestUpdateItem model = new FriendUpdateRequestUpdateItem();

    /**
     * Model tests for FriendUpdateRequestUpdateItem
     */
    @Test
    public void testFriendUpdateRequestUpdateItem() {
        // TODO: test FriendUpdateRequestUpdateItem
    }

    /**
     * Test the property 'toAccount'
     */
    @Test
    public void toAccountTest() {
        // TODO: test toAccount
    }

    /**
     * Test the property 'snsItem'
     */
    @Test
    public void snsItemTest() {
        // TODO: test snsItem
    }

}
