/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetC2cUnreadMsgNumResponseAllOfC2CUnreadMsgNumList
 */
public class GetC2cUnreadMsgNumResponseAllOfC2CUnreadMsgNumListTest {
    private final GetC2cUnreadMsgNumResponseAllOfC2CUnreadMsgNumList model = new GetC2cUnreadMsgNumResponseAllOfC2CUnreadMsgNumList();

    /**
     * Model tests for GetC2cUnreadMsgNumResponseAllOfC2CUnreadMsgNumList
     */
    @Test
    public void testGetC2cUnreadMsgNumResponseAllOfC2CUnreadMsgNumList() {
        // TODO: test GetC2cUnreadMsgNumResponseAllOfC2CUnreadMsgNumList
    }

    /**
     * Test the property 'peerAccount'
     */
    @Test
    public void peerAccountTest() {
        // TODO: test peerAccount
    }

    /**
     * Test the property 'c2CUnreadMsgNum'
     */
    @Test
    public void c2CUnreadMsgNumTest() {
        // TODO: test c2CUnreadMsgNum
    }

}
