/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.GetC2cUnreadMsgNumResponseAllOfC2CUnreadMsgNumList;
import com.tencentcloudapi.im.model.GetC2cUnreadMsgNumResponseAllOfErrorList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetC2cUnreadMsgNumResponseAllOf
 */
public class GetC2cUnreadMsgNumResponseAllOfTest {
    private final GetC2cUnreadMsgNumResponseAllOf model = new GetC2cUnreadMsgNumResponseAllOf();

    /**
     * Model tests for GetC2cUnreadMsgNumResponseAllOf
     */
    @Test
    public void testGetC2cUnreadMsgNumResponseAllOf() {
        // TODO: test GetC2cUnreadMsgNumResponseAllOf
    }

    /**
     * Test the property 'allC2CUnreadMsgNum'
     */
    @Test
    public void allC2CUnreadMsgNumTest() {
        // TODO: test allC2CUnreadMsgNum
    }

    /**
     * Test the property 'c2CUnreadMsgNumList'
     */
    @Test
    public void c2CUnreadMsgNumListTest() {
        // TODO: test c2CUnreadMsgNumList
    }

    /**
     * Test the property 'errorList'
     */
    @Test
    public void errorListTest() {
        // TODO: test errorList
    }

}
