/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetGroupMemberInfoResponseAllOfAppMemberDefinedData
 */
public class GetGroupMemberInfoResponseAllOfAppMemberDefinedDataTest {
    private final GetGroupMemberInfoResponseAllOfAppMemberDefinedData model = new GetGroupMemberInfoResponseAllOfAppMemberDefinedData();

    /**
     * Model tests for GetGroupMemberInfoResponseAllOfAppMemberDefinedData
     */
    @Test
    public void testGetGroupMemberInfoResponseAllOfAppMemberDefinedData() {
        // TODO: test GetGroupMemberInfoResponseAllOfAppMemberDefinedData
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
