/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetGroupInfoRequestResponseFilter
 */
public class GetGroupInfoRequestResponseFilterTest {
    private final GetGroupInfoRequestResponseFilter model = new GetGroupInfoRequestResponseFilter();

    /**
     * Model tests for GetGroupInfoRequestResponseFilter
     */
    @Test
    public void testGetGroupInfoRequestResponseFilter() {
        // TODO: test GetGroupInfoRequestResponseFilter
    }

    /**
     * Test the property 'groupBaseInfoFilter'
     */
    @Test
    public void groupBaseInfoFilterTest() {
        // TODO: test groupBaseInfoFilter
    }

    /**
     * Test the property 'memberInfoFilter'
     */
    @Test
    public void memberInfoFilterTest() {
        // TODO: test memberInfoFilter
    }

    /**
     * Test the property 'appDefinedDataFilterGroup'
     */
    @Test
    public void appDefinedDataFilterGroupTest() {
        // TODO: test appDefinedDataFilterGroup
    }

    /**
     * Test the property 'appDefinedDataFilterGroupMember'
     */
    @Test
    public void appDefinedDataFilterGroupMemberTest() {
        // TODO: test appDefinedDataFilterGroupMember
    }

}
