/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetGroupMemberInfoRequest
 */
public class GetGroupMemberInfoRequestTest {
    private final GetGroupMemberInfoRequest model = new GetGroupMemberInfoRequest();

    /**
     * Model tests for GetGroupMemberInfoRequest
     */
    @Test
    public void testGetGroupMemberInfoRequest() {
        // TODO: test GetGroupMemberInfoRequest
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'memberInfoFilter'
     */
    @Test
    public void memberInfoFilterTest() {
        // TODO: test memberInfoFilter
    }

    /**
     * Test the property 'memberRoleFilter'
     */
    @Test
    public void memberRoleFilterTest() {
        // TODO: test memberRoleFilter
    }

    /**
     * Test the property 'appDefinedDataFilterGroupMember'
     */
    @Test
    public void appDefinedDataFilterGroupMemberTest() {
        // TODO: test appDefinedDataFilterGroupMember
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'next'
     */
    @Test
    public void nextTest() {
        // TODO: test next
    }

}
