/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.GetJoinedGroupListRequestResponseFilter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetJoinedGroupListRequest
 */
public class GetJoinedGroupListRequestTest {
    private final GetJoinedGroupListRequest model = new GetJoinedGroupListRequest();

    /**
     * Model tests for GetJoinedGroupListRequest
     */
    @Test
    public void testGetJoinedGroupListRequest() {
        // TODO: test GetJoinedGroupListRequest
    }

    /**
     * Test the property 'memberAccount'
     */
    @Test
    public void memberAccountTest() {
        // TODO: test memberAccount
    }

    /**
     * Test the property 'withHugeGroups'
     */
    @Test
    public void withHugeGroupsTest() {
        // TODO: test withHugeGroups
    }

    /**
     * Test the property 'withNoActiveGroups'
     */
    @Test
    public void withNoActiveGroupsTest() {
        // TODO: test withNoActiveGroups
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'groupType'
     */
    @Test
    public void groupTypeTest() {
        // TODO: test groupType
    }

    /**
     * Test the property 'responseFilter'
     */
    @Test
    public void responseFilterTest() {
        // TODO: test responseFilter
    }

}
