/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetOperateMsgHistoryResponseAllOfFile
 */
public class GetOperateMsgHistoryResponseAllOfFileTest {
    private final GetOperateMsgHistoryResponseAllOfFile model = new GetOperateMsgHistoryResponseAllOfFile();

    /**
     * Model tests for GetOperateMsgHistoryResponseAllOfFile
     */
    @Test
    public void testGetOperateMsgHistoryResponseAllOfFile() {
        // TODO: test GetOperateMsgHistoryResponseAllOfFile
    }

    /**
     * Test the property 'URL'
     */
    @Test
    public void URLTest() {
        // TODO: test URL
    }

    /**
     * Test the property 'expireTime'
     */
    @Test
    public void expireTimeTest() {
        // TODO: test expireTime
    }

    /**
     * Test the property 'fileSize'
     */
    @Test
    public void fileSizeTest() {
        // TODO: test fileSize
    }

    /**
     * Test the property 'fileMD5'
     */
    @Test
    public void fileMD5Test() {
        // TODO: test fileMD5
    }

    /**
     * Test the property 'gzipSize'
     */
    @Test
    public void gzipSizeTest() {
        // TODO: test gzipSize
    }

    /**
     * Test the property 'gzipMD5'
     */
    @Test
    public void gzipMD5Test() {
        // TODO: test gzipMD5
    }

}
