/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.CommonResponse;
import com.tencentcloudapi.im.model.GetRoamMsgResponseAllOf;
import com.tencentcloudapi.im.model.GetRoamMsgResponseAllOfMsgList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetRoamMsgResponse
 */
public class GetRoamMsgResponseTest {
    private final GetRoamMsgResponse model = new GetRoamMsgResponse();

    /**
     * Model tests for GetRoamMsgResponse
     */
    @Test
    public void testGetRoamMsgResponse() {
        // TODO: test GetRoamMsgResponse
    }

    /**
     * Test the property 'actionStatus'
     */
    @Test
    public void actionStatusTest() {
        // TODO: test actionStatus
    }

    /**
     * Test the property 'errorInfo'
     */
    @Test
    public void errorInfoTest() {
        // TODO: test errorInfo
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'complete'
     */
    @Test
    public void completeTest() {
        // TODO: test complete
    }

    /**
     * Test the property 'msgCnt'
     */
    @Test
    public void msgCntTest() {
        // TODO: test msgCnt
    }

    /**
     * Test the property 'lastMsgTime'
     */
    @Test
    public void lastMsgTimeTest() {
        // TODO: test lastMsgTime
    }

    /**
     * Test the property 'lastMsgKey'
     */
    @Test
    public void lastMsgKeyTest() {
        // TODO: test lastMsgKey
    }

    /**
     * Test the property 'msgList'
     */
    @Test
    public void msgListTest() {
        // TODO: test msgList
    }

}
