/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetRoleInGroupResponseAllOfUserIdList
 */
public class GetRoleInGroupResponseAllOfUserIdListTest {
    private final GetRoleInGroupResponseAllOfUserIdList model = new GetRoleInGroupResponseAllOfUserIdList();

    /**
     * Model tests for GetRoleInGroupResponseAllOfUserIdList
     */
    @Test
    public void testGetRoleInGroupResponseAllOfUserIdList() {
        // TODO: test GetRoleInGroupResponseAllOfUserIdList
    }

    /**
     * Test the property 'memberAccount'
     */
    @Test
    public void memberAccountTest() {
        // TODO: test memberAccount
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

}
