/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetRecentContactListGroupDeleteRequest
 */
public class GetRecentContactListGroupDeleteRequestTest {
    private final GetRecentContactListGroupDeleteRequest model = new GetRecentContactListGroupDeleteRequest();

    /**
     * Model tests for GetRecentContactListGroupDeleteRequest
     */
    @Test
    public void testGetRecentContactListGroupDeleteRequest() {
        // TODO: test GetRecentContactListGroupDeleteRequest
    }

    /**
     * Test the property 'fromAccount'
     */
    @Test
    public void fromAccountTest() {
        // TODO: test fromAccount
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'toAccount'
     */
    @Test
    public void toAccountTest() {
        // TODO: test toAccount
    }

    /**
     * Test the property 'toGroupid'
     */
    @Test
    public void toGroupidTest() {
        // TODO: test toGroupid
    }

    /**
     * Test the property 'clearRamble'
     */
    @Test
    public void clearRambleTest() {
        // TODO: test clearRamble
    }

}
