/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.TIMMsgElement;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GroupMsgGetSimpleResponseAllOfRspMsgList
 */
public class GroupMsgGetSimpleResponseAllOfRspMsgListTest {
    private final GroupMsgGetSimpleResponseAllOfRspMsgList model = new GroupMsgGetSimpleResponseAllOfRspMsgList();

    /**
     * Model tests for GroupMsgGetSimpleResponseAllOfRspMsgList
     */
    @Test
    public void testGroupMsgGetSimpleResponseAllOfRspMsgList() {
        // TODO: test GroupMsgGetSimpleResponseAllOfRspMsgList
    }

    /**
     * Test the property 'fromAccount'
     */
    @Test
    public void fromAccountTest() {
        // TODO: test fromAccount
    }

    /**
     * Test the property 'isPlaceMsg'
     */
    @Test
    public void isPlaceMsgTest() {
        // TODO: test isPlaceMsg
    }

    /**
     * Test the property 'msgPriority'
     */
    @Test
    public void msgPriorityTest() {
        // TODO: test msgPriority
    }

    /**
     * Test the property 'msgRandom'
     */
    @Test
    public void msgRandomTest() {
        // TODO: test msgRandom
    }

    /**
     * Test the property 'msgSeq'
     */
    @Test
    public void msgSeqTest() {
        // TODO: test msgSeq
    }

    /**
     * Test the property 'msgTimeStamp'
     */
    @Test
    public void msgTimeStampTest() {
        // TODO: test msgTimeStamp
    }

    /**
     * Test the property 'msgBody'
     */
    @Test
    public void msgBodyTest() {
        // TODO: test msgBody
    }

    /**
     * Test the property 'isSystemMsg'
     */
    @Test
    public void isSystemMsgTest() {
        // TODO: test isSystemMsg
    }

}
