/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.GroupMsgGetSimpleResponseAllOfRspMsgList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GroupMsgGetSimpleResponseAllOf
 */
public class GroupMsgGetSimpleResponseAllOfTest {
    private final GroupMsgGetSimpleResponseAllOf model = new GroupMsgGetSimpleResponseAllOf();

    /**
     * Model tests for GroupMsgGetSimpleResponseAllOf
     */
    @Test
    public void testGroupMsgGetSimpleResponseAllOf() {
        // TODO: test GroupMsgGetSimpleResponseAllOf
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'isFinished'
     */
    @Test
    public void isFinishedTest() {
        // TODO: test isFinished
    }

    /**
     * Test the property 'rspMsgList'
     */
    @Test
    public void rspMsgListTest() {
        // TODO: test rspMsgList
    }

}
