/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GroupDeleteResponseAllOf
 */
public class GroupDeleteResponseAllOfTest {
    private final GroupDeleteResponseAllOf model = new GroupDeleteResponseAllOf();

    /**
     * Model tests for GroupDeleteResponseAllOf
     */
    @Test
    public void testGroupDeleteResponseAllOf() {
        // TODO: test GroupDeleteResponseAllOf
    }

    /**
     * Test the property 'currentSequence'
     */
    @Test
    public void currentSequenceTest() {
        // TODO: test currentSequence
    }

    /**
     * Test the property 'errorDisplay'
     */
    @Test
    public void errorDisplayTest() {
        // TODO: test errorDisplay
    }

}
