/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ImGetAttrResponseAllOfUserAttrs
 */
public class ImGetAttrResponseAllOfUserAttrsTest {
    private final ImGetAttrResponseAllOfUserAttrs model = new ImGetAttrResponseAllOfUserAttrs();

    /**
     * Model tests for ImGetAttrResponseAllOfUserAttrs
     */
    @Test
    public void testImGetAttrResponseAllOfUserAttrs() {
        // TODO: test ImGetAttrResponseAllOfUserAttrs
    }

    /**
     * Test the property 'toAccount'
     */
    @Test
    public void toAccountTest() {
        // TODO: test toAccount
    }

    /**
     * Test the property 'attrs'
     */
    @Test
    public void attrsTest() {
        // TODO: test attrs
    }

}
