/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ImportGroupMemberRequestMemberList
 */
public class ImportGroupMemberRequestMemberListTest {
    private final ImportGroupMemberRequestMemberList model = new ImportGroupMemberRequestMemberList();

    /**
     * Model tests for ImportGroupMemberRequestMemberList
     */
    @Test
    public void testImportGroupMemberRequestMemberList() {
        // TODO: test ImportGroupMemberRequestMemberList
    }

    /**
     * Test the property 'memberAccount'
     */
    @Test
    public void memberAccountTest() {
        // TODO: test memberAccount
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'joinTime'
     */
    @Test
    public void joinTimeTest() {
        // TODO: test joinTime
    }

    /**
     * Test the property 'unreadMsgNum'
     */
    @Test
    public void unreadMsgNumTest() {
        // TODO: test unreadMsgNum
    }

}
