/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.TIMMsgElement;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ImportGroupMsgRequest
 */
public class ImportGroupMsgRequestTest {
    private final ImportGroupMsgRequest model = new ImportGroupMsgRequest();

    /**
     * Model tests for ImportGroupMsgRequest
     */
    @Test
    public void testImportGroupMsgRequest() {
        // TODO: test ImportGroupMsgRequest
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'recentContactFlag'
     */
    @Test
    public void recentContactFlagTest() {
        // TODO: test recentContactFlag
    }

    /**
     * Test the property 'msgList'
     */
    @Test
    public void msgListTest() {
        // TODO: test msgList
    }

    /**
     * Test the property 'fromAccount'
     */
    @Test
    public void fromAccountTest() {
        // TODO: test fromAccount
    }

    /**
     * Test the property 'sendTime'
     */
    @Test
    public void sendTimeTest() {
        // TODO: test sendTime
    }

    /**
     * Test the property 'random'
     */
    @Test
    public void randomTest() {
        // TODO: test random
    }

    /**
     * Test the property 'msgBody'
     */
    @Test
    public void msgBodyTest() {
        // TODO: test msgBody
    }

}
