/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tencentcloudapi.im.model.TIMMsgElement;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ImportGroupMsgRequestMsgList
 */
public class ImportGroupMsgRequestMsgListTest {
    private final ImportGroupMsgRequestMsgList model = new ImportGroupMsgRequestMsgList();

    /**
     * Model tests for ImportGroupMsgRequestMsgList
     */
    @Test
    public void testImportGroupMsgRequestMsgList() {
        // TODO: test ImportGroupMsgRequestMsgList
    }

    /**
     * Test the property 'fromAccount'
     */
    @Test
    public void fromAccountTest() {
        // TODO: test fromAccount
    }

    /**
     * Test the property 'sendTime'
     */
    @Test
    public void sendTimeTest() {
        // TODO: test sendTime
    }

    /**
     * Test the property 'random'
     */
    @Test
    public void randomTest() {
        // TODO: test random
    }

    /**
     * Test the property 'msgBody'
     */
    @Test
    public void msgBodyTest() {
        // TODO: test msgBody
    }

}
