/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ImPushRequestCondition
 */
public class ImPushRequestConditionTest {
    private final ImPushRequestCondition model = new ImPushRequestCondition();

    /**
     * Model tests for ImPushRequestCondition
     */
    @Test
    public void testImPushRequestCondition() {
        // TODO: test ImPushRequestCondition
    }

    /**
     * Test the property 'attrsOr'
     */
    @Test
    public void attrsOrTest() {
        // TODO: test attrsOr
    }

    /**
     * Test the property 'attrsAnd'
     */
    @Test
    public void attrsAndTest() {
        // TODO: test attrsAnd
    }

    /**
     * Test the property 'tagsOr'
     */
    @Test
    public void tagsOrTest() {
        // TODO: test tagsOr
    }

    /**
     * Test the property 'tagsAnd'
     */
    @Test
    public void tagsAndTest() {
        // TODO: test tagsAnd
    }

}
