/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ImPushRequestConditionInner
 */
public class ImPushRequestConditionInnerTest {
    private final ImPushRequestConditionInner model = new ImPushRequestConditionInner();

    /**
     * Model tests for ImPushRequestConditionInner
     */
    @Test
    public void testImPushRequestConditionInner() {
        // TODO: test ImPushRequestConditionInner
    }

    /**
     * Test the property 'attrsOr'
     */
    @Test
    public void attrsOrTest() {
        // TODO: test attrsOr
    }

    /**
     * Test the property 'attrsAnd'
     */
    @Test
    public void attrsAndTest() {
        // TODO: test attrsAnd
    }

    /**
     * Test the property 'tagsOr'
     */
    @Test
    public void tagsOrTest() {
        // TODO: test tagsOr
    }

    /**
     * Test the property 'tagsAnd'
     */
    @Test
    public void tagsAndTest() {
        // TODO: test tagsAnd
    }

}
