/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.ModifyGroupMemberInfoRequestAppMemberDefinedDataInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ModifyGroupMemberInfoRequest
 */
public class ModifyGroupMemberInfoRequestTest {
    private final ModifyGroupMemberInfoRequest model = new ModifyGroupMemberInfoRequest();

    /**
     * Model tests for ModifyGroupMemberInfoRequest
     */
    @Test
    public void testModifyGroupMemberInfoRequest() {
        // TODO: test ModifyGroupMemberInfoRequest
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'memberAccount'
     */
    @Test
    public void memberAccountTest() {
        // TODO: test memberAccount
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'msgFlag'
     */
    @Test
    public void msgFlagTest() {
        // TODO: test msgFlag
    }

    /**
     * Test the property 'nameCard'
     */
    @Test
    public void nameCardTest() {
        // TODO: test nameCard
    }

    /**
     * Test the property 'appMemberDefinedData'
     */
    @Test
    public void appMemberDefinedDataTest() {
        // TODO: test appMemberDefinedData
    }

    /**
     * Test the property 'shutUpTime'
     */
    @Test
    public void shutUpTimeTest() {
        // TODO: test shutUpTime
    }

}
