/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.OfflinePushInfoAndroidInfo;
import com.tencentcloudapi.im.model.OfflinePushInfoApnsInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OfflinePushInfo
 */
public class OfflinePushInfoTest {
    private final OfflinePushInfo model = new OfflinePushInfo();

    /**
     * Model tests for OfflinePushInfo
     */
    @Test
    public void testOfflinePushInfo() {
        // TODO: test OfflinePushInfo
    }

    /**
     * Test the property 'pushFlag'
     */
    @Test
    public void pushFlagTest() {
        // TODO: test pushFlag
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'desc'
     */
    @Test
    public void descTest() {
        // TODO: test desc
    }

    /**
     * Test the property 'ext'
     */
    @Test
    public void extTest() {
        // TODO: test ext
    }

    /**
     * Test the property 'androidInfo'
     */
    @Test
    public void androidInfoTest() {
        // TODO: test androidInfo
    }

    /**
     * Test the property 'apnsInfo'
     */
    @Test
    public void apnsInfoTest() {
        // TODO: test apnsInfo
    }

}
