/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.CommonResponse;
import com.tencentcloudapi.im.model.PortraitGetResponseAllOf;
import com.tencentcloudapi.im.model.PortraitGetResponseAllOfUserProfileItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PortraitGetResponse
 */
public class PortraitGetResponseTest {
    private final PortraitGetResponse model = new PortraitGetResponse();

    /**
     * Model tests for PortraitGetResponse
     */
    @Test
    public void testPortraitGetResponse() {
        // TODO: test PortraitGetResponse
    }

    /**
     * Test the property 'actionStatus'
     */
    @Test
    public void actionStatusTest() {
        // TODO: test actionStatus
    }

    /**
     * Test the property 'errorInfo'
     */
    @Test
    public void errorInfoTest() {
        // TODO: test errorInfo
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'userProfileItem'
     */
    @Test
    public void userProfileItemTest() {
        // TODO: test userProfileItem
    }

    /**
     * Test the property 'failAccount'
     */
    @Test
    public void failAccountTest() {
        // TODO: test failAccount
    }

    /**
     * Test the property 'errorDisplay'
     */
    @Test
    public void errorDisplayTest() {
        // TODO: test errorDisplay
    }

}
