/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SetMsgReadRequest
 */
public class SetMsgReadRequestTest {
    private final SetMsgReadRequest model = new SetMsgReadRequest();

    /**
     * Model tests for SetMsgReadRequest
     */
    @Test
    public void testSetMsgReadRequest() {
        // TODO: test SetMsgReadRequest
    }

    /**
     * Test the property 'reportAccount'
     */
    @Test
    public void reportAccountTest() {
        // TODO: test reportAccount
    }

    /**
     * Test the property 'peerAccount'
     */
    @Test
    public void peerAccountTest() {
        // TODO: test peerAccount
    }

    /**
     * Test the property 'msgReadTime'
     */
    @Test
    public void msgReadTimeTest() {
        // TODO: test msgReadTime
    }

}
