/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.tencentcloudapi.im.model.TIMSoundElemMsgContent;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TIMSoundElem
 */
public class TIMSoundElemTest {
    private final TIMSoundElem model = new TIMSoundElem();

    /**
     * Model tests for TIMSoundElem
     */
    @Test
    public void testTIMSoundElem() {
        // TODO: test TIMSoundElem
    }

    /**
     * Test the property 'msgType'
     */
    @Test
    public void msgTypeTest() {
        // TODO: test msgType
    }

    /**
     * Test the property 'msgContent'
     */
    @Test
    public void msgContentTest() {
        // TODO: test msgContent
    }

}
