/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tencentcloudapi.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TIMVideoFileElemMsgContent
 */
public class TIMVideoFileElemMsgContentTest {
    private final TIMVideoFileElemMsgContent model = new TIMVideoFileElemMsgContent();

    /**
     * Model tests for TIMVideoFileElemMsgContent
     */
    @Test
    public void testTIMVideoFileElemMsgContent() {
        // TODO: test TIMVideoFileElemMsgContent
    }

    /**
     * Test the property 'videoUrl'
     */
    @Test
    public void videoUrlTest() {
        // TODO: test videoUrl
    }

    /**
     * Test the property 'videoUUID'
     */
    @Test
    public void videoUUIDTest() {
        // TODO: test videoUUID
    }

    /**
     * Test the property 'videoSize'
     */
    @Test
    public void videoSizeTest() {
        // TODO: test videoSize
    }

    /**
     * Test the property 'videoSecond'
     */
    @Test
    public void videoSecondTest() {
        // TODO: test videoSecond
    }

    /**
     * Test the property 'videoFormat'
     */
    @Test
    public void videoFormatTest() {
        // TODO: test videoFormat
    }

    /**
     * Test the property 'videoDownloadFlag'
     */
    @Test
    public void videoDownloadFlagTest() {
        // TODO: test videoDownloadFlag
    }

    /**
     * Test the property 'thumbUrl'
     */
    @Test
    public void thumbUrlTest() {
        // TODO: test thumbUrl
    }

    /**
     * Test the property 'thumbUUID'
     */
    @Test
    public void thumbUUIDTest() {
        // TODO: test thumbUUID
    }

    /**
     * Test the property 'thumbSize'
     */
    @Test
    public void thumbSizeTest() {
        // TODO: test thumbSize
    }

    /**
     * Test the property 'thumbWidth'
     */
    @Test
    public void thumbWidthTest() {
        // TODO: test thumbWidth
    }

    /**
     * Test the property 'thumbHeight'
     */
    @Test
    public void thumbHeightTest() {
        // TODO: test thumbHeight
    }

    /**
     * Test the property 'thumbFormat'
     */
    @Test
    public void thumbFormatTest() {
        // TODO: test thumbFormat
    }

    /**
     * Test the property 'thumbDownloadFlag'
     */
    @Test
    public void thumbDownloadFlagTest() {
        // TODO: test thumbDownloadFlag
    }

}
