/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountImportRequest
 */
public class AccountImportRequestTest {
    private final AccountImportRequest model = new AccountImportRequest();

    /**
     * Model tests for AccountImportRequest
     */
    @Test
    public void testAccountImportRequest() {
        // TODO: test AccountImportRequest
    }

    /**
     * Test the property 'userID'
     */
    @Test
    public void userIDTest() {
        // TODO: test userID
    }

    /**
     * Test the property 'nick'
     */
    @Test
    public void nickTest() {
        // TODO: test nick
    }

    /**
     * Test the property 'faceUrl'
     */
    @Test
    public void faceUrlTest() {
        // TODO: test faceUrl
    }

}
