/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.AddGroupMemberRequestMemberListInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddGroupMemberRequest
 */
public class AddGroupMemberRequestTest {
    private final AddGroupMemberRequest model = new AddGroupMemberRequest();

    /**
     * Model tests for AddGroupMemberRequest
     */
    @Test
    public void testAddGroupMemberRequest() {
        // TODO: test AddGroupMemberRequest
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'silence'
     */
    @Test
    public void silenceTest() {
        // TODO: test silence
    }

    /**
     * Test the property 'memberList'
     */
    @Test
    public void memberListTest() {
        // TODO: test memberList
    }

}
