/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.BlackListDeleteResponseAllOf;
import tencentcloud.im.model.BlackListDeleteResponseAllOfResultItem;
import tencentcloud.im.model.CommonResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BlackListDeleteResponse
 */
public class BlackListDeleteResponseTest {
    private final BlackListDeleteResponse model = new BlackListDeleteResponse();

    /**
     * Model tests for BlackListDeleteResponse
     */
    @Test
    public void testBlackListDeleteResponse() {
        // TODO: test BlackListDeleteResponse
    }

    /**
     * Test the property 'actionStatus'
     */
    @Test
    public void actionStatusTest() {
        // TODO: test actionStatus
    }

    /**
     * Test the property 'errorInfo'
     */
    @Test
    public void errorInfoTest() {
        // TODO: test errorInfo
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'resultItem'
     */
    @Test
    public void resultItemTest() {
        // TODO: test resultItem
    }

    /**
     * Test the property 'failAccount'
     */
    @Test
    public void failAccountTest() {
        // TODO: test failAccount
    }

    /**
     * Test the property 'errorDisplay'
     */
    @Test
    public void errorDisplayTest() {
        // TODO: test errorDisplay
    }

}
