/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ForbidSendMsgRequest
 */
public class ForbidSendMsgRequestTest {
    private final ForbidSendMsgRequest model = new ForbidSendMsgRequest();

    /**
     * Model tests for ForbidSendMsgRequest
     */
    @Test
    public void testForbidSendMsgRequest() {
        // TODO: test ForbidSendMsgRequest
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'membersAccount'
     */
    @Test
    public void membersAccountTest() {
        // TODO: test membersAccount
    }

    /**
     * Test the property 'shutUpTime'
     */
    @Test
    public void shutUpTimeTest() {
        // TODO: test shutUpTime
    }

}
