/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.FriendImportRequestAddFriendItemInnerCustomItemInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FriendImportRequestAddFriendItemInner
 */
public class FriendImportRequestAddFriendItemInnerTest {
    private final FriendImportRequestAddFriendItemInner model = new FriendImportRequestAddFriendItemInner();

    /**
     * Model tests for FriendImportRequestAddFriendItemInner
     */
    @Test
    public void testFriendImportRequestAddFriendItemInner() {
        // TODO: test FriendImportRequestAddFriendItemInner
    }

    /**
     * Test the property 'toAccount'
     */
    @Test
    public void toAccountTest() {
        // TODO: test toAccount
    }

    /**
     * Test the property 'remark'
     */
    @Test
    public void remarkTest() {
        // TODO: test remark
    }

    /**
     * Test the property 'remarkTime'
     */
    @Test
    public void remarkTimeTest() {
        // TODO: test remarkTime
    }

    /**
     * Test the property 'groupName'
     */
    @Test
    public void groupNameTest() {
        // TODO: test groupName
    }

    /**
     * Test the property 'addSource'
     */
    @Test
    public void addSourceTest() {
        // TODO: test addSource
    }

    /**
     * Test the property 'addWording'
     */
    @Test
    public void addWordingTest() {
        // TODO: test addWording
    }

    /**
     * Test the property 'addTime'
     */
    @Test
    public void addTimeTest() {
        // TODO: test addTime
    }

    /**
     * Test the property 'customItem'
     */
    @Test
    public void customItemTest() {
        // TODO: test customItem
    }

}
