/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetAppInfoResponseAllOfResult
 */
public class GetAppInfoResponseAllOfResultTest {
    private final GetAppInfoResponseAllOfResult model = new GetAppInfoResponseAllOfResult();

    /**
     * Model tests for GetAppInfoResponseAllOfResult
     */
    @Test
    public void testGetAppInfoResponseAllOfResult() {
        // TODO: test GetAppInfoResponseAllOfResult
    }

    /**
     * Test the property 'appName'
     */
    @Test
    public void appNameTest() {
        // TODO: test appName
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'activeUserNum'
     */
    @Test
    public void activeUserNumTest() {
        // TODO: test activeUserNum
    }

    /**
     * Test the property 'registUserNumOneDay'
     */
    @Test
    public void registUserNumOneDayTest() {
        // TODO: test registUserNumOneDay
    }

    /**
     * Test the property 'registUserNumTotal'
     */
    @Test
    public void registUserNumTotalTest() {
        // TODO: test registUserNumTotal
    }

    /**
     * Test the property 'loginTimes'
     */
    @Test
    public void loginTimesTest() {
        // TODO: test loginTimes
    }

    /**
     * Test the property 'loginUserNum'
     */
    @Test
    public void loginUserNumTest() {
        // TODO: test loginUserNum
    }

    /**
     * Test the property 'upMsgNum'
     */
    @Test
    public void upMsgNumTest() {
        // TODO: test upMsgNum
    }

    /**
     * Test the property 'sendMsgUserNum'
     */
    @Test
    public void sendMsgUserNumTest() {
        // TODO: test sendMsgUserNum
    }

    /**
     * Test the property 'apNSMsgNum'
     */
    @Test
    public void apNSMsgNumTest() {
        // TODO: test apNSMsgNum
    }

    /**
     * Test the property 'c2CUpMsgNum'
     */
    @Test
    public void c2CUpMsgNumTest() {
        // TODO: test c2CUpMsgNum
    }

    /**
     * Test the property 'c2CDownMsgNum'
     */
    @Test
    public void c2CDownMsgNumTest() {
        // TODO: test c2CDownMsgNum
    }

    /**
     * Test the property 'c2CSendMsgUserNum'
     */
    @Test
    public void c2CSendMsgUserNumTest() {
        // TODO: test c2CSendMsgUserNum
    }

    /**
     * Test the property 'c2CAPNSMsgNum'
     */
    @Test
    public void c2CAPNSMsgNumTest() {
        // TODO: test c2CAPNSMsgNum
    }

    /**
     * Test the property 'maxOnlineNum'
     */
    @Test
    public void maxOnlineNumTest() {
        // TODO: test maxOnlineNum
    }

    /**
     * Test the property 'downMsgNum'
     */
    @Test
    public void downMsgNumTest() {
        // TODO: test downMsgNum
    }

    /**
     * Test the property 'chainIncrease'
     */
    @Test
    public void chainIncreaseTest() {
        // TODO: test chainIncrease
    }

    /**
     * Test the property 'chainDecrease'
     */
    @Test
    public void chainDecreaseTest() {
        // TODO: test chainDecrease
    }

    /**
     * Test the property 'groupUpMsgNum'
     */
    @Test
    public void groupUpMsgNumTest() {
        // TODO: test groupUpMsgNum
    }

    /**
     * Test the property 'groupDownMsgNum'
     */
    @Test
    public void groupDownMsgNumTest() {
        // TODO: test groupDownMsgNum
    }

    /**
     * Test the property 'groupSendMsgUserNum'
     */
    @Test
    public void groupSendMsgUserNumTest() {
        // TODO: test groupSendMsgUserNum
    }

    /**
     * Test the property 'groupAPNSMsgNum'
     */
    @Test
    public void groupAPNSMsgNumTest() {
        // TODO: test groupAPNSMsgNum
    }

    /**
     * Test the property 'groupSendMsgGroupNum'
     */
    @Test
    public void groupSendMsgGroupNumTest() {
        // TODO: test groupSendMsgGroupNum
    }

    /**
     * Test the property 'groupJoinGroupTimes'
     */
    @Test
    public void groupJoinGroupTimesTest() {
        // TODO: test groupJoinGroupTimes
    }

    /**
     * Test the property 'groupQuitGroupTimes'
     */
    @Test
    public void groupQuitGroupTimesTest() {
        // TODO: test groupQuitGroupTimes
    }

    /**
     * Test the property 'groupNewGroupNum'
     */
    @Test
    public void groupNewGroupNumTest() {
        // TODO: test groupNewGroupNum
    }

    /**
     * Test the property 'groupAllGroupNum'
     */
    @Test
    public void groupAllGroupNumTest() {
        // TODO: test groupAllGroupNum
    }

    /**
     * Test the property 'groupDestroyGroupNum'
     */
    @Test
    public void groupDestroyGroupNumTest() {
        // TODO: test groupDestroyGroupNum
    }

    /**
     * Test the property 'callBackReq'
     */
    @Test
    public void callBackReqTest() {
        // TODO: test callBackReq
    }

    /**
     * Test the property 'callBackRsp'
     */
    @Test
    public void callBackRspTest() {
        // TODO: test callBackRsp
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

}
