/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.CommonResponse;
import tencentcloud.im.model.GetC2cUnreadMsgNumResponseAllOf;
import tencentcloud.im.model.GetC2cUnreadMsgNumResponseAllOfC2CUnreadMsgNumList;
import tencentcloud.im.model.GetC2cUnreadMsgNumResponseAllOfErrorList;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetC2cUnreadMsgNumResponse
 */
public class GetC2cUnreadMsgNumResponseTest {
    private final GetC2cUnreadMsgNumResponse model = new GetC2cUnreadMsgNumResponse();

    /**
     * Model tests for GetC2cUnreadMsgNumResponse
     */
    @Test
    public void testGetC2cUnreadMsgNumResponse() {
        // TODO: test GetC2cUnreadMsgNumResponse
    }

    /**
     * Test the property 'actionStatus'
     */
    @Test
    public void actionStatusTest() {
        // TODO: test actionStatus
    }

    /**
     * Test the property 'errorInfo'
     */
    @Test
    public void errorInfoTest() {
        // TODO: test errorInfo
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'allC2CUnreadMsgNum'
     */
    @Test
    public void allC2CUnreadMsgNumTest() {
        // TODO: test allC2CUnreadMsgNum
    }

    /**
     * Test the property 'c2CUnreadMsgNumList'
     */
    @Test
    public void c2CUnreadMsgNumListTest() {
        // TODO: test c2CUnreadMsgNumList
    }

    /**
     * Test the property 'errorList'
     */
    @Test
    public void errorListTest() {
        // TODO: test errorList
    }

}
