/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetC2cUnreadMsgNumResponseAllOfErrorList
 */
public class GetC2cUnreadMsgNumResponseAllOfErrorListTest {
    private final GetC2cUnreadMsgNumResponseAllOfErrorList model = new GetC2cUnreadMsgNumResponseAllOfErrorList();

    /**
     * Model tests for GetC2cUnreadMsgNumResponseAllOfErrorList
     */
    @Test
    public void testGetC2cUnreadMsgNumResponseAllOfErrorList() {
        // TODO: test GetC2cUnreadMsgNumResponseAllOfErrorList
    }

    /**
     * Test the property 'peerAccount'
     */
    @Test
    public void peerAccountTest() {
        // TODO: test peerAccount
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

}
