/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.GetGroupInfoResponseAllOfGroupInfo;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetGroupInfoResponseAllOf
 */
public class GetGroupInfoResponseAllOfTest {
    private final GetGroupInfoResponseAllOf model = new GetGroupInfoResponseAllOf();

    /**
     * Model tests for GetGroupInfoResponseAllOf
     */
    @Test
    public void testGetGroupInfoResponseAllOf() {
        // TODO: test GetGroupInfoResponseAllOf
    }

    /**
     * Test the property 'groupInfo'
     */
    @Test
    public void groupInfoTest() {
        // TODO: test groupInfo
    }

}
