/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetGroupMemberInfoResponseAllOfMemberList
 */
public class GetGroupMemberInfoResponseAllOfMemberListTest {
    private final GetGroupMemberInfoResponseAllOfMemberList model = new GetGroupMemberInfoResponseAllOfMemberList();

    /**
     * Model tests for GetGroupMemberInfoResponseAllOfMemberList
     */
    @Test
    public void testGetGroupMemberInfoResponseAllOfMemberList() {
        // TODO: test GetGroupMemberInfoResponseAllOfMemberList
    }

    /**
     * Test the property 'memberAccount'
     */
    @Test
    public void memberAccountTest() {
        // TODO: test memberAccount
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'joinTime'
     */
    @Test
    public void joinTimeTest() {
        // TODO: test joinTime
    }

    /**
     * Test the property 'msgSeq'
     */
    @Test
    public void msgSeqTest() {
        // TODO: test msgSeq
    }

    /**
     * Test the property 'msgFlag'
     */
    @Test
    public void msgFlagTest() {
        // TODO: test msgFlag
    }

    /**
     * Test the property 'lastSendMsgTime'
     */
    @Test
    public void lastSendMsgTimeTest() {
        // TODO: test lastSendMsgTime
    }

    /**
     * Test the property 'nameCard'
     */
    @Test
    public void nameCardTest() {
        // TODO: test nameCard
    }

}
