/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.CommonResponse;
import tencentcloud.im.model.GetGroupMemberInfoResponseAllOf;
import tencentcloud.im.model.GetGroupMemberInfoResponseAllOfAppMemberDefinedData;
import tencentcloud.im.model.GetGroupMemberInfoResponseAllOfMemberList;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetGroupMemberInfoResponse
 */
public class GetGroupMemberInfoResponseTest {
    private final GetGroupMemberInfoResponse model = new GetGroupMemberInfoResponse();

    /**
     * Model tests for GetGroupMemberInfoResponse
     */
    @Test
    public void testGetGroupMemberInfoResponse() {
        // TODO: test GetGroupMemberInfoResponse
    }

    /**
     * Test the property 'actionStatus'
     */
    @Test
    public void actionStatusTest() {
        // TODO: test actionStatus
    }

    /**
     * Test the property 'errorInfo'
     */
    @Test
    public void errorInfoTest() {
        // TODO: test errorInfo
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'memberNum'
     */
    @Test
    public void memberNumTest() {
        // TODO: test memberNum
    }

    /**
     * Test the property 'memberList'
     */
    @Test
    public void memberListTest() {
        // TODO: test memberList
    }

    /**
     * Test the property 'appMemberDefinedData'
     */
    @Test
    public void appMemberDefinedDataTest() {
        // TODO: test appMemberDefinedData
    }

    /**
     * Test the property 'next'
     */
    @Test
    public void nextTest() {
        // TODO: test next
    }

}
