/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetJoinedGroupListResponseAllOfGroupIdList
 */
public class GetJoinedGroupListResponseAllOfGroupIdListTest {
    private final GetJoinedGroupListResponseAllOfGroupIdList model = new GetJoinedGroupListResponseAllOfGroupIdList();

    /**
     * Model tests for GetJoinedGroupListResponseAllOfGroupIdList
     */
    @Test
    public void testGetJoinedGroupListResponseAllOfGroupIdList() {
        // TODO: test GetJoinedGroupListResponseAllOfGroupIdList
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'introduction'
     */
    @Test
    public void introductionTest() {
        // TODO: test introduction
    }

    /**
     * Test the property 'notification'
     */
    @Test
    public void notificationTest() {
        // TODO: test notification
    }

    /**
     * Test the property 'faceUrl'
     */
    @Test
    public void faceUrlTest() {
        // TODO: test faceUrl
    }

    /**
     * Test the property 'ownerAccount'
     */
    @Test
    public void ownerAccountTest() {
        // TODO: test ownerAccount
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'infoSeq'
     */
    @Test
    public void infoSeqTest() {
        // TODO: test infoSeq
    }

    /**
     * Test the property 'lastInfoTime'
     */
    @Test
    public void lastInfoTimeTest() {
        // TODO: test lastInfoTime
    }

    /**
     * Test the property 'lastMsgTime'
     */
    @Test
    public void lastMsgTimeTest() {
        // TODO: test lastMsgTime
    }

    /**
     * Test the property 'nextMsgSeq'
     */
    @Test
    public void nextMsgSeqTest() {
        // TODO: test nextMsgSeq
    }

    /**
     * Test the property 'memberNum'
     */
    @Test
    public void memberNumTest() {
        // TODO: test memberNum
    }

    /**
     * Test the property 'maxMemberNum'
     */
    @Test
    public void maxMemberNumTest() {
        // TODO: test maxMemberNum
    }

    /**
     * Test the property 'applyJoinOption'
     */
    @Test
    public void applyJoinOptionTest() {
        // TODO: test applyJoinOption
    }

}
