/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetNoSpeakingResponseAllOf
 */
public class GetNoSpeakingResponseAllOfTest {
    private final GetNoSpeakingResponseAllOf model = new GetNoSpeakingResponseAllOf();

    /**
     * Model tests for GetNoSpeakingResponseAllOf
     */
    @Test
    public void testGetNoSpeakingResponseAllOf() {
        // TODO: test GetNoSpeakingResponseAllOf
    }

    /**
     * Test the property 'c2CmsgNospeakingTime'
     */
    @Test
    public void c2CmsgNospeakingTimeTest() {
        // TODO: test c2CmsgNospeakingTime
    }

    /**
     * Test the property 'groupmsgNospeakingTime'
     */
    @Test
    public void groupmsgNospeakingTimeTest() {
        // TODO: test groupmsgNospeakingTime
    }

}
