/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import tencentcloud.im.model.CommonResponse;
import tencentcloud.im.model.GetOnlineMemberNumResponseAllOf;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetOnlineMemberNumResponse
 */
public class GetOnlineMemberNumResponseTest {
    private final GetOnlineMemberNumResponse model = new GetOnlineMemberNumResponse();

    /**
     * Model tests for GetOnlineMemberNumResponse
     */
    @Test
    public void testGetOnlineMemberNumResponse() {
        // TODO: test GetOnlineMemberNumResponse
    }

    /**
     * Test the property 'actionStatus'
     */
    @Test
    public void actionStatusTest() {
        // TODO: test actionStatus
    }

    /**
     * Test the property 'errorInfo'
     */
    @Test
    public void errorInfoTest() {
        // TODO: test errorInfo
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'onlineMemberNum'
     */
    @Test
    public void onlineMemberNumTest() {
        // TODO: test onlineMemberNum
    }

}
