/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetOperateMsgHistoryRequest
 */
public class GetOperateMsgHistoryRequestTest {
    private final GetOperateMsgHistoryRequest model = new GetOperateMsgHistoryRequest();

    /**
     * Model tests for GetOperateMsgHistoryRequest
     */
    @Test
    public void testGetOperateMsgHistoryRequest() {
        // TODO: test GetOperateMsgHistoryRequest
    }

    /**
     * Test the property 'chatType'
     */
    @Test
    public void chatTypeTest() {
        // TODO: test chatType
    }

    /**
     * Test the property 'msgTime'
     */
    @Test
    public void msgTimeTest() {
        // TODO: test msgTime
    }

}
