/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetOnlineMemberNumResponseAllOf
 */
public class GetOnlineMemberNumResponseAllOfTest {
    private final GetOnlineMemberNumResponseAllOf model = new GetOnlineMemberNumResponseAllOf();

    /**
     * Model tests for GetOnlineMemberNumResponseAllOf
     */
    @Test
    public void testGetOnlineMemberNumResponseAllOf() {
        // TODO: test GetOnlineMemberNumResponseAllOf
    }

    /**
     * Test the property 'onlineMemberNum'
     */
    @Test
    public void onlineMemberNumTest() {
        // TODO: test onlineMemberNum
    }

}
