/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetRecentContactListGroupGetRequest
 */
public class GetRecentContactListGroupGetRequestTest {
    private final GetRecentContactListGroupGetRequest model = new GetRecentContactListGroupGetRequest();

    /**
     * Model tests for GetRecentContactListGroupGetRequest
     */
    @Test
    public void testGetRecentContactListGroupGetRequest() {
        // TODO: test GetRecentContactListGroupGetRequest
    }

    /**
     * Test the property 'fromAccount'
     */
    @Test
    public void fromAccountTest() {
        // TODO: test fromAccount
    }

    /**
     * Test the property 'timeStamp'
     */
    @Test
    public void timeStampTest() {
        // TODO: test timeStamp
    }

    /**
     * Test the property 'startIndex'
     */
    @Test
    public void startIndexTest() {
        // TODO: test startIndex
    }

    /**
     * Test the property 'topTimeStamp'
     */
    @Test
    public void topTimeStampTest() {
        // TODO: test topTimeStamp
    }

    /**
     * Test the property 'topStartIndex'
     */
    @Test
    public void topStartIndexTest() {
        // TODO: test topStartIndex
    }

    /**
     * Test the property 'assistFlags'
     */
    @Test
    public void assistFlagsTest() {
        // TODO: test assistFlags
    }

}
