/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.TIMMsgElement;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetRoamMsgResponseAllOfMsgList
 */
public class GetRoamMsgResponseAllOfMsgListTest {
    private final GetRoamMsgResponseAllOfMsgList model = new GetRoamMsgResponseAllOfMsgList();

    /**
     * Model tests for GetRoamMsgResponseAllOfMsgList
     */
    @Test
    public void testGetRoamMsgResponseAllOfMsgList() {
        // TODO: test GetRoamMsgResponseAllOfMsgList
    }

    /**
     * Test the property 'fromAccount'
     */
    @Test
    public void fromAccountTest() {
        // TODO: test fromAccount
    }

    /**
     * Test the property 'toAccount'
     */
    @Test
    public void toAccountTest() {
        // TODO: test toAccount
    }

    /**
     * Test the property 'msgRandom'
     */
    @Test
    public void msgRandomTest() {
        // TODO: test msgRandom
    }

    /**
     * Test the property 'msgTimeStamp'
     */
    @Test
    public void msgTimeStampTest() {
        // TODO: test msgTimeStamp
    }

    /**
     * Test the property 'msgFlagBits'
     */
    @Test
    public void msgFlagBitsTest() {
        // TODO: test msgFlagBits
    }

    /**
     * Test the property 'msgKey'
     */
    @Test
    public void msgKeyTest() {
        // TODO: test msgKey
    }

    /**
     * Test the property 'msgBody'
     */
    @Test
    public void msgBodyTest() {
        // TODO: test msgBody
    }

    /**
     * Test the property 'cloudCustomData'
     */
    @Test
    public void cloudCustomDataTest() {
        // TODO: test cloudCustomData
    }

}
