/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.CommonResponse;
import tencentcloud.im.model.GroupMsgGetSimpleResponseAllOf;
import tencentcloud.im.model.GroupMsgGetSimpleResponseAllOfRspMsgList;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GroupMsgGetSimpleResponse
 */
public class GroupMsgGetSimpleResponseTest {
    private final GroupMsgGetSimpleResponse model = new GroupMsgGetSimpleResponse();

    /**
     * Model tests for GroupMsgGetSimpleResponse
     */
    @Test
    public void testGroupMsgGetSimpleResponse() {
        // TODO: test GroupMsgGetSimpleResponse
    }

    /**
     * Test the property 'actionStatus'
     */
    @Test
    public void actionStatusTest() {
        // TODO: test actionStatus
    }

    /**
     * Test the property 'errorInfo'
     */
    @Test
    public void errorInfoTest() {
        // TODO: test errorInfo
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'isFinished'
     */
    @Test
    public void isFinishedTest() {
        // TODO: test isFinished
    }

    /**
     * Test the property 'rspMsgList'
     */
    @Test
    public void rspMsgListTest() {
        // TODO: test rspMsgList
    }

}
