/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import tencentcloud.im.model.CommonResponse;
import tencentcloud.im.model.GroupDeleteResponseAllOf;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GroupDeleteResponse
 */
public class GroupDeleteResponseTest {
    private final GroupDeleteResponse model = new GroupDeleteResponse();

    /**
     * Model tests for GroupDeleteResponse
     */
    @Test
    public void testGroupDeleteResponse() {
        // TODO: test GroupDeleteResponse
    }

    /**
     * Test the property 'actionStatus'
     */
    @Test
    public void actionStatusTest() {
        // TODO: test actionStatus
    }

    /**
     * Test the property 'errorInfo'
     */
    @Test
    public void errorInfoTest() {
        // TODO: test errorInfo
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'currentSequence'
     */
    @Test
    public void currentSequenceTest() {
        // TODO: test currentSequence
    }

    /**
     * Test the property 'errorDisplay'
     */
    @Test
    public void errorDisplayTest() {
        // TODO: test errorDisplay
    }

}
