/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GroupMsgGetSimpleRequest
 */
public class GroupMsgGetSimpleRequestTest {
    private final GroupMsgGetSimpleRequest model = new GroupMsgGetSimpleRequest();

    /**
     * Model tests for GroupMsgGetSimpleRequest
     */
    @Test
    public void testGroupMsgGetSimpleRequest() {
        // TODO: test GroupMsgGetSimpleRequest
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'reqMsgNumber'
     */
    @Test
    public void reqMsgNumberTest() {
        // TODO: test reqMsgNumber
    }

    /**
     * Test the property 'reqMsgSeq'
     */
    @Test
    public void reqMsgSeqTest() {
        // TODO: test reqMsgSeq
    }

    /**
     * Test the property 'withRecalledMsg'
     */
    @Test
    public void withRecalledMsgTest() {
        // TODO: test withRecalledMsg
    }

}
