/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.GroupAddResponseAllOfResultItem;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GroupAddResponseAllOf
 */
public class GroupAddResponseAllOfTest {
    private final GroupAddResponseAllOf model = new GroupAddResponseAllOf();

    /**
     * Model tests for GroupAddResponseAllOf
     */
    @Test
    public void testGroupAddResponseAllOf() {
        // TODO: test GroupAddResponseAllOf
    }

    /**
     * Test the property 'resultItem'
     */
    @Test
    public void resultItemTest() {
        // TODO: test resultItem
    }

    /**
     * Test the property 'failAccount'
     */
    @Test
    public void failAccountTest() {
        // TODO: test failAccount
    }

    /**
     * Test the property 'currentSequence'
     */
    @Test
    public void currentSequenceTest() {
        // TODO: test currentSequence
    }

    /**
     * Test the property 'errorDisplay'
     */
    @Test
    public void errorDisplayTest() {
        // TODO: test errorDisplay
    }

}
