/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.DefinedData;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ImportGroupRequest
 */
public class ImportGroupRequestTest {
    private final ImportGroupRequest model = new ImportGroupRequest();

    /**
     * Model tests for ImportGroupRequest
     */
    @Test
    public void testImportGroupRequest() {
        // TODO: test ImportGroupRequest
    }

    /**
     * Test the property 'ownerAccount'
     */
    @Test
    public void ownerAccountTest() {
        // TODO: test ownerAccount
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'introduction'
     */
    @Test
    public void introductionTest() {
        // TODO: test introduction
    }

    /**
     * Test the property 'notification'
     */
    @Test
    public void notificationTest() {
        // TODO: test notification
    }

    /**
     * Test the property 'faceUrl'
     */
    @Test
    public void faceUrlTest() {
        // TODO: test faceUrl
    }

    /**
     * Test the property 'maxMemberCount'
     */
    @Test
    public void maxMemberCountTest() {
        // TODO: test maxMemberCount
    }

    /**
     * Test the property 'applyJoinOption'
     */
    @Test
    public void applyJoinOptionTest() {
        // TODO: test applyJoinOption
    }

    /**
     * Test the property 'appDefinedData'
     */
    @Test
    public void appDefinedDataTest() {
        // TODO: test appDefinedData
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

}
