/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ImportGroupMemberRequestMemberListInner
 */
public class ImportGroupMemberRequestMemberListInnerTest {
    private final ImportGroupMemberRequestMemberListInner model = new ImportGroupMemberRequestMemberListInner();

    /**
     * Model tests for ImportGroupMemberRequestMemberListInner
     */
    @Test
    public void testImportGroupMemberRequestMemberListInner() {
        // TODO: test ImportGroupMemberRequestMemberListInner
    }

    /**
     * Test the property 'memberAccount'
     */
    @Test
    public void memberAccountTest() {
        // TODO: test memberAccount
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'joinTime'
     */
    @Test
    public void joinTimeTest() {
        // TODO: test joinTime
    }

    /**
     * Test the property 'unreadMsgNum'
     */
    @Test
    public void unreadMsgNumTest() {
        // TODO: test unreadMsgNum
    }

}
