/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OfflinePushInfoApnsInfo
 */
public class OfflinePushInfoApnsInfoTest {
    private final OfflinePushInfoApnsInfo model = new OfflinePushInfoApnsInfo();

    /**
     * Model tests for OfflinePushInfoApnsInfo
     */
    @Test
    public void testOfflinePushInfoApnsInfo() {
        // TODO: test OfflinePushInfoApnsInfo
    }

    /**
     * Test the property 'badgeMode'
     */
    @Test
    public void badgeModeTest() {
        // TODO: test badgeMode
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'subTitle'
     */
    @Test
    public void subTitleTest() {
        // TODO: test subTitle
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'mutableContent'
     */
    @Test
    public void mutableContentTest() {
        // TODO: test mutableContent
    }

}
