/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OfflinePushInfoAndroidInfo
 */
public class OfflinePushInfoAndroidInfoTest {
    private final OfflinePushInfoAndroidInfo model = new OfflinePushInfoAndroidInfo();

    /**
     * Model tests for OfflinePushInfoAndroidInfo
     */
    @Test
    public void testOfflinePushInfoAndroidInfo() {
        // TODO: test OfflinePushInfoAndroidInfo
    }

    /**
     * Test the property 'sound'
     */
    @Test
    public void soundTest() {
        // TODO: test sound
    }

    /**
     * Test the property 'huaWeiChannelID'
     */
    @Test
    public void huaWeiChannelIDTest() {
        // TODO: test huaWeiChannelID
    }

    /**
     * Test the property 'xiaoMiChannelID'
     */
    @Test
    public void xiaoMiChannelIDTest() {
        // TODO: test xiaoMiChannelID
    }

    /**
     * Test the property 'opPOChannelID'
     */
    @Test
    public void opPOChannelIDTest() {
        // TODO: test opPOChannelID
    }

    /**
     * Test the property 'googleChannelID'
     */
    @Test
    public void googleChannelIDTest() {
        // TODO: test googleChannelID
    }

    /**
     * Test the property 'viVOClassification'
     */
    @Test
    public void viVOClassificationTest() {
        // TODO: test viVOClassification
    }

    /**
     * Test the property 'huaWeiImportance'
     */
    @Test
    public void huaWeiImportanceTest() {
        // TODO: test huaWeiImportance
    }

    /**
     * Test the property 'extAsHuaweiIntentParam'
     */
    @Test
    public void extAsHuaweiIntentParamTest() {
        // TODO: test extAsHuaweiIntentParam
    }

}
