/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.PortraitGetResponseAllOfProfileItem;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PortraitGetResponseAllOfUserProfileItem
 */
public class PortraitGetResponseAllOfUserProfileItemTest {
    private final PortraitGetResponseAllOfUserProfileItem model = new PortraitGetResponseAllOfUserProfileItem();

    /**
     * Model tests for PortraitGetResponseAllOfUserProfileItem
     */
    @Test
    public void testPortraitGetResponseAllOfUserProfileItem() {
        // TODO: test PortraitGetResponseAllOfUserProfileItem
    }

    /**
     * Test the property 'toAccount'
     */
    @Test
    public void toAccountTest() {
        // TODO: test toAccount
    }

    /**
     * Test the property 'profileItem'
     */
    @Test
    public void profileItemTest() {
        // TODO: test profileItem
    }

    /**
     * Test the property 'resultCode'
     */
    @Test
    public void resultCodeTest() {
        // TODO: test resultCode
    }

    /**
     * Test the property 'resultInfo'
     */
    @Test
    public void resultInfoTest() {
        // TODO: test resultInfo
    }

}
