/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.QueryOnlineStatusResponseAllOfErrorList;
import tencentcloud.im.model.QueryOnlineStatusResponseAllOfQueryResult;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for QueryOnlineStatusResponseAllOf
 */
public class QueryOnlineStatusResponseAllOfTest {
    private final QueryOnlineStatusResponseAllOf model = new QueryOnlineStatusResponseAllOf();

    /**
     * Model tests for QueryOnlineStatusResponseAllOf
     */
    @Test
    public void testQueryOnlineStatusResponseAllOf() {
        // TODO: test QueryOnlineStatusResponseAllOf
    }

    /**
     * Test the property 'queryResult'
     */
    @Test
    public void queryResultTest() {
        // TODO: test queryResult
    }

    /**
     * Test the property 'errorList'
     */
    @Test
    public void errorListTest() {
        // TODO: test errorList
    }

}
