/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SendMsgControl
 */
public class SendMsgControlTest {
    /**
     * Model tests for SendMsgControl
     */
    @Test
    public void testSendMsgControl() {
        // TODO: test SendMsgControl
    }

}
