/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.ForbidCallbackControl;
import tencentcloud.im.model.OfflinePushInfo;
import tencentcloud.im.model.SendMsgControl;
import tencentcloud.im.model.TIMMsgElement;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SendGroupMsgRequest
 */
public class SendGroupMsgRequestTest {
    private final SendGroupMsgRequest model = new SendGroupMsgRequest();

    /**
     * Model tests for SendGroupMsgRequest
     */
    @Test
    public void testSendGroupMsgRequest() {
        // TODO: test SendGroupMsgRequest
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'random'
     */
    @Test
    public void randomTest() {
        // TODO: test random
    }

    /**
     * Test the property 'msgPriority'
     */
    @Test
    public void msgPriorityTest() {
        // TODO: test msgPriority
    }

    /**
     * Test the property 'msgBody'
     */
    @Test
    public void msgBodyTest() {
        // TODO: test msgBody
    }

    /**
     * Test the property 'fromAccount'
     */
    @Test
    public void fromAccountTest() {
        // TODO: test fromAccount
    }

    /**
     * Test the property 'offlinePushInfo'
     */
    @Test
    public void offlinePushInfoTest() {
        // TODO: test offlinePushInfo
    }

    /**
     * Test the property 'forbidCallbackControl'
     */
    @Test
    public void forbidCallbackControlTest() {
        // TODO: test forbidCallbackControl
    }

    /**
     * Test the property 'onlineOnlyFlag'
     */
    @Test
    public void onlineOnlyFlagTest() {
        // TODO: test onlineOnlyFlag
    }

    /**
     * Test the property 'sendMsgControl'
     */
    @Test
    public void sendMsgControlTest() {
        // TODO: test sendMsgControl
    }

    /**
     * Test the property 'cloudCustomData'
     */
    @Test
    public void cloudCustomDataTest() {
        // TODO: test cloudCustomData
    }

}
