/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TIMCustomElemMsgContent
 */
public class TIMCustomElemMsgContentTest {
    private final TIMCustomElemMsgContent model = new TIMCustomElemMsgContent();

    /**
     * Model tests for TIMCustomElemMsgContent
     */
    @Test
    public void testTIMCustomElemMsgContent() {
        // TODO: test TIMCustomElemMsgContent
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'desc'
     */
    @Test
    public void descTest() {
        // TODO: test desc
    }

    /**
     * Test the property 'ext'
     */
    @Test
    public void extTest() {
        // TODO: test ext
    }

    /**
     * Test the property 'sound'
     */
    @Test
    public void soundTest() {
        // TODO: test sound
    }

}
