/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import tencentcloud.im.model.TIMFaceElemMsgContent;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TIMFaceElem
 */
public class TIMFaceElemTest {
    private final TIMFaceElem model = new TIMFaceElem();

    /**
     * Model tests for TIMFaceElem
     */
    @Test
    public void testTIMFaceElem() {
        // TODO: test TIMFaceElem
    }

    /**
     * Test the property 'msgType'
     */
    @Test
    public void msgTypeTest() {
        // TODO: test msgType
    }

    /**
     * Test the property 'msgContent'
     */
    @Test
    public void msgContentTest() {
        // TODO: test msgContent
    }

}
