/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tencentcloud.im.model.ImageInfo;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TIMImageElemMsgContent
 */
public class TIMImageElemMsgContentTest {
    private final TIMImageElemMsgContent model = new TIMImageElemMsgContent();

    /**
     * Model tests for TIMImageElemMsgContent
     */
    @Test
    public void testTIMImageElemMsgContent() {
        // TODO: test TIMImageElemMsgContent
    }

    /**
     * Test the property 'UUID'
     */
    @Test
    public void UUIDTest() {
        // TODO: test UUID
    }

    /**
     * Test the property 'imageFormat'
     */
    @Test
    public void imageFormatTest() {
        // TODO: test imageFormat
    }

    /**
     * Test the property 'imageInfoArray'
     */
    @Test
    public void imageInfoArrayTest() {
        // TODO: test imageInfoArray
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'URL'
     */
    @Test
    public void URLTest() {
        // TODO: test URL
    }

}
