/*
 * TIM SERVER REST API SDK
 * TIM REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tencentcloud.im.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import tencentcloud.im.model.TIMCustomElem;
import tencentcloud.im.model.TIMFaceElem;
import tencentcloud.im.model.TIMFileElem;
import tencentcloud.im.model.TIMImageElem;
import tencentcloud.im.model.TIMLocationElem;
import tencentcloud.im.model.TIMSoundElem;
import tencentcloud.im.model.TIMTextElem;
import tencentcloud.im.model.TIMVideoFileElem;
import tencentcloud.im.model.TIMVideoFileElemMsgContent;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TIMMsgElement
 */
public class TIMMsgElementTest {
    private final TIMMsgElement model = new TIMMsgElement();

    /**
     * Model tests for TIMMsgElement
     */
    @Test
    public void testTIMMsgElement() {
        // TODO: test TIMMsgElement
    }

    /**
     * Test the property 'msgType'
     */
    @Test
    public void msgTypeTest() {
        // TODO: test msgType
    }

    /**
     * Test the property 'msgContent'
     */
    @Test
    public void msgContentTest() {
        // TODO: test msgContent
    }

}
